### ISSUE TITLE
Unable to add new modules

### ISSUE THREAD

**Issue by grevych** [rgst-io/stencil#103]
Hi folks! Ex-Outreach here. Thanks for the effort you are putting into this 🫶 

I tried a few days ago the latest rc `0.7.0-rc.2` and seems it's no longer possible to add a new module once the lock file is in place. The only way I found to add them is through a fresh execution (removing the lock file). I tried the new `upgrade` command but seems it skips new modules.

I added a quick fix to the latter in case it helps #104

**Comment by jaredallard** [comment]
Oh, wow, good catch! Totally missed this use case!

**Comment by jaredallard** [comment]
`upgrade` now supports new modules, thanks to #104. I'll leave this open until `stencil` by itself also does.

**Comment by jaredallard** [comment]
Fixing/tracking as part of the work I'm doing for https://github.com/rgst-io/stencil/issues/114
