### ISSUE TITLE
Failing to render template "stencil-base"

### ISSUE THREAD

**Issue by rblin081** [rgst-io/stencil#141]
When following https://stencil.rgst.io/guide/base-project.html#step-3-import-a-module locally I receive error

`ERRO failed to run error="failed to render template \"github.com/getoutreach/stencil-base/.github/CODEOWNERS.tpl\": template: github.com/getoutreach/stencil-base/.github/CODEOWNERS.tpl:2:24: executing \"github.com/getoutreach/stencil-base/.github/CODEOWNERS.tpl\" at <.Runtime.Box.Org>: can't evaluate field Box in type codegen.runtime"`

Output of the stencil version
```
hello-world % stencil --version
   _____ __                  _ __
  / ___// /____  ____  _____(_) /
  \__ \/ __/ _ \/ __ \/ ___/ / /
 ___/ / /_/  __/ / / / /__/ / /
/____/\__/\___/_/ /_/\___/_/_/

stencil: A modern living-template engine for evolving repositories
https://stencil.rgst.io

GitVersion:    0.9.0
GitCommit:     cca6d78fa9006be26fb1759b2f58ef45b1929106
GitTreeState:  clean
BuildDate:     2024-08-13T05:31:30Z
BuiltBy:       goreleaser
GoVersion:     go1.22.5
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64
```

**Comment by jaredallard** [comment]
Ah sorry about this! Our "getting started" docs are a bit stale since they largely originate from a time where this was part of the `getoutreach` org. I'll take a pass at that today and get it cleaned up! 😄

**Comment by jaredallard** [comment]
This should be resolved now! Let me know how your getting started experience goes 🚀
