### ISSUE TITLE
Feature Request - Configurable comments

### ISSUE THREAD

**Issue by rblin081** [rgst-io/stencil#145]
stencil assumes rendered templates will be used with Go syntax with a comment beginning with `//`

It would be ideal to specify which comment syntax is used with each template, for example in a python file
```
# <<Stencil::Block(pythonImports)>>

# <</Stencil::Block>>
print("Hello World")
# <<Stencil::Block(customMethods)>>

# <</Stencil::Block>>
```

**Comment by jaredallard** [comment]
👋  We actually do support different comments! However, it's slightly opinionated. https://github.com/rgst-io/stencil/blob/main/internal/codegen/blocks.go#L39

You'd want to use either:

* `##`
* `//`
* `--`
* `<!--`

The 'double' requirement comes from trying to make it more obvious back in the `v1` block days, but I don't think we need that anymore so we could probably change it to be `#` instead!
