### ISSUE TITLE
Documentation for "block" is missing

### ISSUE THREAD

**Issue by neenhouse** [rgst-io/stencil#154]
The documentation for block https://github.com/rgst-io/stencil/blob/main/docs/functions/file.Block.md is not showing up on https://stencil.rgst.io/functions/file.Block.html

![CleanShot 2024-09-27 at 11 02 08@2x](https://github.com/user-attachments/assets/c4384584-0625-42e5-9221-31409a10b3cc)

**Comment by jaredallard** [comment]
Yeah there's something horribly wrong with the static sites link handling. It's always failing to load a direct link.

So, workaround:

* Click that link.
* Click "file.Create". Hit CMD+R (or Ctrl+R)
* Watch as "file.Create" is broke
* Click "file.Block", now it loads 🤷 

Anyways, that's absurd, so I'll try to figure this out 😆

**Comment by jaredallard** [comment]
This is now fixed!
