### ISSUE TITLE
Support templates that only render in the initial generation

### ISSUE THREAD

**Issue by erincgucer** [rgst-io/stencil#86]
There are cases when a file (or directory) has to be rendered only on the initial generation of the template, aka when stencil.lock file does not exist.

One example use case of this is when we want to create some conventional directories (for example a "service" directory which would contain business logic classes) for a spring boot microservice. As GitHub does not take empty directories into consideration, in order to create those directories at the very beginning, we need to put at least one file in them. (for example a README.md). After the initial creation though, that placeholder file would eventually be deleted or replaced by other files. (actual business logic classes in our example). So it would not make sense to use file.Static, as the placeholder would already be deleted and we would not want it to be generated all over again and again in the consecutive runs.

**Comment by erincgucer** [comment]
I think this can be done with the following for now;

`{{- if stencil.Exists "stencil.lock" }}
{{- file.Skip "Should only be generated once as a placeholder" }}
{{- end -}}`

**Comment by deregtd** [comment]
That'll just do the very first run tho -- if you add a new template that is this one-time behavior to a module and re-run later, it won't make it once.  So we still need to figure out a strong notion of how to handle this within stencil.

**Comment by jaredallard** [comment]
I'll need to think about this one for a bit before I take it on, but as a work around, the following should work:

```go
{{- $stencilLock := stencil.ReadFile "stencil.lock" | fromYaml }}
{{- range $stencilLock.files }}
{{- if eq .name "fileName }}
{{- file.Skip "Already generated once }}
{{- end }}
```

**Comment by jaredallard** [comment]
This was added in v0.7.0 by @deregtd as [`file.Once`](https://stencil.rgst.io/functions/file.Once.html)! Please re-open if you notice anything not working
